Repository finos/legend-pure, pull requests merged in 2021-12, with the labels that each got.

#397 Add missing asserts to Java-gen to avoid translating their definition
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/assertLibrary.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/simpleObject.pure
Labels: cla-present

#396 Multi-section Delimited Flat Data
  legend-pure-code-compiled-core-external-format-flatdata/src/main/resources/core_external_format_flatdata/binding/flatDataToPure.pure
  legend-pure-code-compiled-core-external-format-flatdata/src/main/resources/core_external_format_flatdata/binding/pureToFlatData.pure
  legend-pure-code-compiled-core-external-format-flatdata/src/main/resources/core_external_format_flatdata/binding/validation.pure
  legend-pure-code-compiled-core-external-format-flatdata/src/main/resources/core_external_format_flatdata/executionPlan/engine.pure
  legend-pure-code-compiled-core-external-format-flatdata/src/main/resources/core_external_format_flatdata/executionPlan/executionPlan.pure
  legend-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/executionPlan/executionPlan.pure
  legend-pure-code-compiled-core/src/main/resources/core/java/metamodel.pure
  legend-pure-code-compiled-core/src/main/resources/core/java/metamodel_factories.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/stringExtension.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/graphFetchCommon.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/common.pure
  legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/meta/AbstractTestNewAssociation.java
  legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/core/meta/NewAssociation.java
  legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CoreExtensionCompiled.java
  legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/meta/TestNewAssociationCompiled.java
  legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/meta/TestNewAssociationInterpreted.java
Labels: enhancement

#380 Allow deserialization of JSON with missing unused properties
  legend-pure-code-compiled-core-external-format-flatdata/src/main/resources/core_external_format_flatdata/executionPlan/executionPlan.pure
  legend-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/executionPlan/executionPlan.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchInMemory.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/typeInfo.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/typeInfoTest.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testSourceTreeCalc.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/simpleObject.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
Labels: enhancement, cla-present

#394 revertMilestoningTransform on properties when serializing mapping to protocol
  legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/transfers/metamodel_relational.pure
Labels: cla-present

#401 Fix metadata id for lambda functions
  legend-pure-code-java-compiled-core/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/TestIdBuilderCore.java
  legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
  legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/runtime/TestIncrementalCompiler.java
  legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/TestFunction.java
  legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tools/TestGraphPath.java
  legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaSourceCodeGenerator.java
  legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/ProcessorContext.java
  legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/IdBuilder.java
  legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
  legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataLazy.java
  legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/TestMeasureCompiled.java
  legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/constraints/TestConstraintHandlerCompiled.java
  legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/constraints/TestConstraints.java
  legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/TestIdBuilder.java
  legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/asserts/TestAssert.java
  legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/incremental/TestSyntheticNodeCut.java
Labels: cla-present

#407 Introduce user name password auth strategy
  legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/models/metamodel_connection.pure
  legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/transfers/connection_relational.pure
  legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/runtime/connection/authenticationStrategy.pure
Labels: cla-present

#405 Update previous vx_x_x versioned alloy test to latest pure protocol version.
  legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tds/tests/testTDSWindowColumn.pure
Labels: cla-present

#404 Support DROP clause for MemSQL using ROW_NUMBER
  legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/functions/tests/testSliceTakeLimitDrop.pure
  legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
Labels: cla-present
