Repository finos/legend-pure, pull requests merged in 2022-05, with the labels that each got.

#555 Ensure the 'test report' module is not last. To avoid the Sonatype pl…
  legend-pure-test-reports/pom.xml
Labels: cla-present

#556 Add an option to skip yarn build in the pure id elight POM
  legend-pure-ide-light/pom.xml
Labels: cla-present

#557 upgrade Yarn@3.2.0 to fix package resolution and update PureClient URL
  legend-pure-ide-light/src/main/web/.yarn/plugins/@yarnpkg/plugin-constraints.cjs
  legend-pure-ide-light/src/main/web/.yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  legend-pure-ide-light/src/main/web/.yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  legend-pure-ide-light/src/main/web/.yarn/releases/yarn-3.0.1.cjs
  legend-pure-ide-light/src/main/web/.yarn/releases/yarn-3.2.0.cjs
  legend-pure-ide-light/src/main/web/.yarnrc.yml
  legend-pure-ide-light/src/main/web/package.json
  legend-pure-ide-light/src/main/web/packages/legend-pure-ide/src/stores/EditorStore.tsx
  legend-pure-ide-light/src/main/web/yarn.lock
Labels: cla-present

#529 Set useAppliedFunction for propertyMapping and QualifiedProperty for Class
  legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/createInstances.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/shared.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/simple.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/mapping.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/metamodel.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/tools/testProfiles.pure
Labels: bug, cla-present

#535 Improve error message when enum value is not found on enum mapping
  legend-pure-m2-dsl-mapping/src/main/resources/platform/pure/mapping.pure
Labels: cla-present

#554 Add java conventions for pow and decimal divide functions
  legend-pure-code-compiled-core/src/main/resources/core/java/metamodel_factories.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/mathLibrary.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/langLibraryTests.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/mathLibraryTests.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/testUtils.pure
Labels: cla-present

#566 Fix typos in comments in CodeRepository
  legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/repository/CodeRepository.java
Labels: cla-present

#565 add avro generation features
  legend-pure-code-compiled-core/src/main/resources/core/external/format/avro/integration.pure
  legend-pure-code-compiled-core/src/main/resources/core/external/format/avro/metamodel.pure
  legend-pure-code-compiled-core/src/main/resources/core/external/format/avro/serialization_avroSchemaToJSON.pure
  legend-pure-code-compiled-core/src/main/resources/core/external/format/avro/tests/testAvroSchemaGenerator.pure
  legend-pure-code-compiled-core/src/main/resources/core/external/format/avro/tramsformation_avroSchemaGenerator.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/generation.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/generation.pure
Labels: cla-present

#564 Java factory: box primitive number branches to fix type inference
  legend-pure-code-compiled-core/src/main/resources/core/java/metamodel_factories.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/langExtension.pure
Labels: cla-present

#552 Support parameterized tests in pure ide and engine
  legend-pure-code-compiled-core-external-shared/src/test/java/org/finos/legend/pure/code/external/shared/Text_Pure_ExternalFormatShared.java
  legend-pure-code-compiled-core/src/main/resources/core/pure/test/testCollection.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/test/tests/testTestCollection.pure
  legend-pure-code-compiled-core/src/test/java/org/finos/legend/pure/code/core/Test_Pure_Core.java
  legend-pure-code-compiled-tests/src/main/java/org/finos/legend/pure/code/core/compiled/test/PureTestBuilderHelper.java
  legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/execution/test/CallBack.java
  legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/execution/test/ExecuteTests.java
  legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/execution/test/TestNode.java
  legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/execution/test/TestResult.java
  legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/execution/test/TestRun.java
  legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/execution/test/TestCallBack.java
  legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/execution/test/TestCollection.java
  legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/execution/test/TestRunner.java
  legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/execution/test/TestTools.java
  legend-pure-m3-core/src/main/resources/platform/pure/test.pure
  legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/runner/TestTestRunner.java
Labels: cla-present

#558 Add support for db specific types
  legend-pure-m2-store-relational/src/main/resources/platform/relational/relational.pure
Labels: cla-present

#563 Attempt to fix error with partially loaded enum metadata
  legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataLazy.java
Labels: cla-present

#569 Allow extraRepositories to be resource names in PureJarMojo
  legend-pure-maven-compilation-par/pom.xml
  legend-pure-maven-compilation-par/src/main/java/org/finos/legend/pure/maven/par/PureJarMojo.java
  legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataLazy.java
  legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/DistributedBinaryGraphDeserializer.java
Labels: cla-present

#548 Added recursion for ConcreteFuncDef in findExpressionsForFunctionInValueSpecification functionality
  legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/metaExtension.pure
Labels: cla-present

#542 Update Java generation for PureExpressionPlatformExecutionNode
  legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_generation.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/common.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/platform.pure
Labels: bug, cla-present

#560 Fix hacked class 3
  legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/valueSpecification.pure
Labels: cla-present

#534 Add support for union on more than 2 sets
  legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/router/router_cluster.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/router/router_main.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/platform.pure
  legend-pure-code-compiled-core/src/main/resources/core/pure/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/serialize.pure
Labels: cla-present, breaks engine
